name: unit-tests
on: [ push, pull_request ]
jobs:
    norme_test:
        runs-on: ubuntu-latest
        name: unit test
        steps:
          - uses: actions/checkout@v2
          - name: install valgrind
            run:  sudo apt update && sudo apt install -y valgrind
          - name: create folder
            run: |
              mkdir -p gc_collector && mv -f * gc_collector && ls -la
          - name: make tests
            run:  make tests
