name: unit-tests
on: [ push, pull_request ]
jobs:
    norme_test:
        runs-on: ubuntu-latest
        name: unit test
        steps:
          - uses: actions/checkout@v2
          - name: install valgrind
            run:  sudo apt update && sudo apt install -y valgrind
          - name: create folder
            run: mkdir -p gc_collector && mv srcs includes Makefile gc_collector
          - name: make tests
            run:  cd gc_collector && make tests
